export const zh_tw = {
    services: [
        "平面設計",
        "使用者介面設計",
        "影像剪輯",
        "桌面應用程式開發",
        "iOS 應用程式開發",
        "Android 應用程式開發",
        "網頁切版服務",
        "響應式形象官網設計",
        "電子商務系統部署",
        "企業資源規劃系統部署",
    ],
    skills: [
        [
            "CSS (Sass / Less)",
            "Adobe Xd",
            "Adobe Photoshop",
            "Adobe Prmiere Pro",
            "Adobe Illustrator",
            "Adobe After Effects",
        ],
        [
            "React.js",
            "React Native.js",
            "Vue.js",
            "Electron.js",
            "Bootstrap",
            "Wordpress",
        ],
        [
            "Python Django",
            "Python Flask",
            "Koa.js",
            "MongoDB",
            "Docker",
            "Nginx",
        ],
        ["Typescript", "Python", "Javascript", "C++", "Java", "PHP"],
    ],
    pageTitles: [
        "歡迎",
        "關於我",
        "我的技能",
        "設計作品",
        "開發作品",
        "聯絡我",
    ],
};
